/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mpower.springcrud.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.StagedGroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Book service. Represents a row in the &quot;Book&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.mpower.springcrud.model.impl.BookModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.mpower.springcrud.model.impl.BookImpl}.
 * </p>
 *
 * @author mpower
 * @see Book
 * @see com.mpower.springcrud.model.impl.BookImpl
 * @see com.mpower.springcrud.model.impl.BookModelImpl
 * @generated
 */
public interface BookModel extends BaseModel<Book>, StagedGroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a Book System model instance should use the {@link Book} interface instead.
	 */

	/**
	 * Returns the primary key of this Book System.
	 *
	 * @return the primary key of this Book System
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this Book System.
	 *
	 * @param primaryKey the primary key of this Book System
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this Book System.
	 *
	 * @return the uuid of this Book System
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this Book System.
	 *
	 * @param uuid the uuid of this Book System
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the book ID of this Book System.
	 *
	 * @return the book ID of this Book System
	 */
	public long getBookId();

	/**
	 * Sets the book ID of this Book System.
	 *
	 * @param bookId the book ID of this Book System
	 */
	public void setBookId(long bookId);

	/**
	 * Returns the group ID of this Book System.
	 *
	 * @return the group ID of this Book System
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this Book System.
	 *
	 * @param groupId the group ID of this Book System
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this Book System.
	 *
	 * @return the company ID of this Book System
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this Book System.
	 *
	 * @param companyId the company ID of this Book System
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this Book System.
	 *
	 * @return the user ID of this Book System
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this Book System.
	 *
	 * @param userId the user ID of this Book System
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this Book System.
	 *
	 * @return the user uuid of this Book System
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this Book System.
	 *
	 * @param userUuid the user uuid of this Book System
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this Book System.
	 *
	 * @return the user name of this Book System
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this Book System.
	 *
	 * @param userName the user name of this Book System
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this Book System.
	 *
	 * @return the create date of this Book System
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this Book System.
	 *
	 * @param createDate the create date of this Book System
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this Book System.
	 *
	 * @return the modified date of this Book System
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this Book System.
	 *
	 * @param modifiedDate the modified date of this Book System
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the book name of this Book System.
	 *
	 * @return the book name of this Book System
	 */
	@AutoEscape
	public String getBookName();

	/**
	 * Sets the book name of this Book System.
	 *
	 * @param bookName the book name of this Book System
	 */
	public void setBookName(String bookName);

	/**
	 * Returns the author of this Book System.
	 *
	 * @return the author of this Book System
	 */
	@AutoEscape
	public String getAuthor();

	/**
	 * Sets the author of this Book System.
	 *
	 * @param author the author of this Book System
	 */
	public void setAuthor(String author);

	/**
	 * Returns the price of this Book System.
	 *
	 * @return the price of this Book System
	 */
	public double getPrice();

	/**
	 * Sets the price of this Book System.
	 *
	 * @param price the price of this Book System
	 */
	public void setPrice(double price);

	/**
	 * Returns the book type of this Book System.
	 *
	 * @return the book type of this Book System
	 */
	@AutoEscape
	public String getBookType();

	/**
	 * Sets the book type of this Book System.
	 *
	 * @param bookType the book type of this Book System
	 */
	public void setBookType(String bookType);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Book book);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Book> toCacheModel();

	@Override
	public Book toEscapedModel();

	@Override
	public Book toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}